# -*- mode: ruby -*-
# vi: set ft=ruby :

################################################################################
# centos7-x64-m_update_image
#
# Vagrantfile is used to automatically update packages in albmtez/centos7-x64
# Vagrant box, in order to export it and release a new updated version to
# Vagrant Cloud.
################################################################################

$update_script = <<SCRIPT
yum update -y
rm /root/.bash_history
rm /home/vagrant/.bash_history
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "albmtez/centos7-x64"
	config.ssh.insert_key = false
	config.vm.provision "shell", inline: $update_script
	config.vm.provider "virtualbox" do |vb|
		vb.name = "centos7-x64"
	end
end
