Vagrant.configure("2") do |config|
    config.vm.box = "albmtez/debian-9-amd64"
    config.disksize.size = '40GB'
  
    config.ssh.insert_key = false
  
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      vb.name = "debian"
      # Customize the amount of memory on the VM:
      vb.memory = 4096
      vb.cpus = 2
    end
  end